# Generated by Django 5.0 on 2024-06-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0004_category_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='added_by',
        ),
    ]
