# Generated by Django 5.0 on 2024-06-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0005_remove_category_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three')], default='one', max_length=10),
        ),
    ]
