# Generated by Django 5.0 on 2024-06-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0007_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
