# Generated by Django 5.0 on 2024-06-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0008_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
