# Generated by Django 5.0 on 2024-07-03 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0011_pet_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donated_pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
